---
abstract: 'a test which succeeds until a deadline passes ( a time bomb )'
author:
  - 'David Delikat <david-delikat@usa.net>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.31
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200004, CPAN::Meta::Converter version 2.102400'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Test-Bomb
requires:
  Date::Parse: 0
  Test::More: 0
  Test::Tester: 0
version: 0.005
